"""create revolut connection table

Revision ID: af303b269fbe
Revises: b553905a0393
Create Date: 2026-10-02 12:41:07.332546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af303b269fbe'
down_revision: Union[str, Sequence[str], None] = 'b553905a0393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revolut_connections',
    sa.Column('revolut_connection_id', sa.Integer(), nullable=False),
    sa.Column('external_consent_id', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('connected_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connected_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('revolut_connection_id')
    )
    op.create_index(op.f('ix_revolut_connections_revolut_connection_id'), 'revolut_connections', ['revolut_connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revolut_connections_revolut_connection_id'), table_name='revolut_connections')
    op.drop_table('revolut_connections')
    # ### end Alembic commands ###
