"""Create Workspace tables and association table with users

Revision ID: da0c13667443
Revises: cf14ed65f562
Create Date: 2026-09-29 13:03:29.598561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0c13667443'
down_revision: Union[str, Sequence[str], None] = 'cf14ed65f562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('personal', 'business', name='workspacetypeenum'), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_workspaces_workspace_id'), 'workspaces', ['workspace_id'], unique=False)
    op.create_table('workspace_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'employee', name='workspacerole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_users')
    op.drop_index(op.f('ix_workspaces_workspace_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
