"""create accounts table

Revision ID: dff14d94469b
Revises: af303b269fbe
Create Date: 2026-10-02 21:28:57.765780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff14d94469b'
down_revision: Union[str, Sequence[str], None] = 'af303b269fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# to prevent a ValueError : constraint must have a name
# took here: https://stackoverflow.com/questions/62640576/flask-migrate-valueerror-constraint-must-have-a-name
naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['revolut_connections.revolut_connection_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('connection_id')
    )
    with op.batch_alter_table('revolut_connections', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('connected_by_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint("fk_revolut_connections_connected_by_users", type_='foreignkey')
        batch_op.create_foreign_key("fk_revolut_connections_connected_by_id_users", 'users', ['connected_by_id'], ['user_id'])
        batch_op.drop_column('connected_by')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revolut_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connected_by', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint("fk_revolut_connections_connected_by_id_users", type_='foreignkey')
        batch_op.create_foreign_key("fk_revolut_connections_connected_by_users", 'users', ['connected_by'], ['user_id'])
        batch_op.drop_column('connected_by_id')

    op.drop_table('accounts')
    # ### end Alembic commands ###
