"""change transaction's status column to source

Revision ID: f2025b8265e7
Revises: 2b2943e87489
Create Date: 2026-10-04 14:46:03.328268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2025b8265e7'
down_revision: Union[str, Sequence[str], None] = '2b2943e87489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('MANUAL', 'BANK', 'EXPENSE', name='transactionsourceenum'), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=7), nullable=False))
        batch_op.drop_column('source')

    # ### end Alembic commands ###
